### ISSUE TITLE
Warning found

### ISSUE THREAD

**Issue by QB4-dev** [embeddedarm/gpio-sysfs-demo#1]
function 
```C
int gpio_setedge(int gpio, int rising, int falling)
```
has no return

Please add  
```C 
return ret;
``` 
at the end

**Comment by dhildreth** [comment]
Sorry for the delayed response.  We'll get that taken care of.

**Comment by dhildreth** [comment]
Done:
https://github.com/embeddedarm/gpio-sysfs-demo/commit/59805fbe42536fe0a7c5487723d26e723be98d98
